### PR TITLE
Dependency fixes for zoneminder port

### PR DESCRIPTION
**Pull request by josh4trunks**

### CODE REVIEW

**Comment by josh4trunks** [comment]
Hey @abishai 
Thanks for all the work on this port.

Here's a few fixes, please review and comment/merge.
I have alot of other stuff to commit in the future as well.

**Comment by abishai** [comment]
Hello!
Thank you for the pull request. At least I know, that someone need this stuff in FreeBSD. However,
1. Why do you want to add polkit back? It's not required under FreeBSD, it usefull only to Linux to obtain rights from systemd. Patches I included cut polkit from cmake files, allowing ZM to be build.
2. AFAIK, for build infrastructure, ports referenced as rundeps will be pulled before build.

**Comment by josh4trunks** [comment]
1) I noticed my build was failing asking for polkit. maybe the patches weren't applying for me for some reason. I'll double check this when I get the chance.

2) mind linking to where it says that. I though that too, but once again my build was failing asking for some missing perl dependencies.

**Comment by josh4trunks** [comment]
do you have a test system. if so to test point (2) you could delete zoneminder, then some perl dependencies and see if the build does grab them first.

reading here https://www.freebsd.org/doc/en/books/porters-handbook/makefile-depend.html
what I proposed is wrong, lol.

**Comment by abishai** [comment]
Looks like there is the problem indeed. bdeps should be returned.
What about polkit ? I really removed it from cmake lists.

**Comment by josh4trunks** [comment]
k, let's just do as the manual describes and set the build dependencies to a temp variable

Im not at my computer. I'll check if the patch applies properly tonight.

**Comment by josh4trunks** [comment]
ohh, and do you really need ffmpeg>2? if there really is no minimum version we can just use "ffmepg"

**Comment by abishai** [comment]
I fixed build deps.
I'm not sure about ffmpeg. Isn't ffmpeg1 very old?

**Comment by josh4trunks** [comment]
it is old, but if its not actually a requirement why even put it?

**Comment by josh4trunks** [comment]
I believe I found the reason the patch wasn't applying. You named the file `patch_CMakeLists.txt` when it should be `patch-CMakeLists.txt`. I'm not sure why it's working fine on your system, maybe because you have polkit installed from previous attempts.

Anyway, I'm going to close this PR. rebase my fork with your fixes, and create a new PR.

**Pull request closed without merging**
