### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by josh4trunks**
Fix some typos/grammer
Note, I changed the 6 Gb to 6 GB. I assume you meant 6 gigabytes, if you meant gigabits I recommend we change this to 0.75 GB or 750 MB as bits is not a common way to measure disk/memory storage.

### CODE REVIEW

**Comment by josh4trunks** [comment]
Hey @abishai 
when you have a chance can you review/comment/merge?

Thanks,

**Comment by abishai** [comment]
I'm in China now and have huge problems with spare time  and internet access. I will review it, eventually.

**Comment by josh4trunks** [comment]
no worries! just making sure it doesn't get forgotten

**Comment by abishai** [comment]
I'm still in China, however have some spare time now. 
I replaced pkg-message to provide some clues to folks choosed not to build DOCS. Current ZM port utilizes the same trick.

**Comment by josh4trunks** [comment]
good point, didn't think of that

**Pull request merged**
